import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header1 from "@/components/headers/header/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header1 />
        <main className="max-w-2xl lg:max-w-4xl m-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
